### ISSUE TITLE
Not loading currency data

### ISSUE THREAD

**Issue by GGRIZLI** [yawnsde/MMM-CurrencyExchange#3]
CurrencyExchange data not loading currency data. Module just say Loading....
If I use API base link in web browser I get Success code and currency data:

{"success":true,"timestamp":1541268250,"base":"EUR","date":"2018-11-03","rates":{"AED":4.183133,"AFN":85.414536,"ALL":125.164694,"AMD":554.451958,"ANG":2.021131,"AOA":352.306471,"ARS":40.407757,"AUD":1.579639,"AWG":2.049939,"AZN":1.938905,"BAM":1.815453,"BBD":2.278051,"BDT":95.486196,"BGN":1.956102,"BHD":0.429012,"BIF":2067.02161,"BMD":1.138855,"BND":1.660497,"BOB":7.890841,"BRL":4.208415,"BSD":1.13857,"BTC":0.000179,"BTN":83.040005,"BWP":12.152035,"BYN":2.413352,"BYR":22321.555676,"BZD":2.2887,"CAD":1.494235,"CDF":1834.695626,"CHF":1.140962,"CLF":0.028525,"CLP":781.031133,"CNY":7.84774,"COP":3627.252797,"CRC":697.993218,"CUC":1.138855,"CUP":30.179654,"CVE":110.739406,"CZK":25.814087,"DJF":202.397738,"DKK":7.460301,"DOP":56.720713,"DZD":134.811993,"EGP":20.394048,"ERN":17.083231,"ETB":32.013657,"EUR":1,"FJD":2.433168,"FKP":0.876907,"GBP":0.877265,"GEL":3.09813,"GGP":0.877978,"GHS":5.513543,"GIP":0.876907,"GMD":56.333502,"GNF":10392.051198,"GTQ":8.796178,"GYD":237.775862,"HKD":8.904764,"HNL":27.600194,"HRK":7.43593,"HTG":82.216786,"HUF":321.863608,"IDR":17029.297042,"ILS":4.208757,"IMP":0.877978,"INR":83.039649,"IQD":1356.376164,"IRR":47951.485183,"ISK":138.314365,"JEP":0.877978,"JMD":145.978858,"JOD":0.808022,"JPY":128.924112,"KES":115.411992,"KGS":79.445041,"KHR":4607.80725,"KMF":492.726002,"KPW":1025.079701,"KRW":1273.240156,"KWD":0.345814,"KYD":0.948872,"KZT":422.538374,"LAK":9737.209634,"LBP":1725.308638,"LKR":196.134023,"LRD":179.227332,"LSL":16.388556,"LTL":3.362743,"LVL":0.688882,"LYD":1.588747,"MAD":10.849306,"MDL":19.513714,"MGA":4014.463852,"MKD":61.343324,"MMK":1824.730666,"MNT":2905.78823,"MOP":9.176214,"MRO":406.571586,"MUR":39.635002,"MVR":17.607127,"MWK":828.260728,"MXN":22.792021,"MYR":4.740488,"MZN":69.191172,"NAD":16.388551,"NGN":413.404714,"NIO":36.728499,"NOK":9.537003,"NPR":131.976242,"NZD":1.710792,"OMR":0.43826,"PAB":1.138684,"PEN":3.82698,"PGK":3.703727,"PHP":60.541952,"PKR":151.866725,"PLN":4.309471,"PYG":6825.670215,"QAR":4.146614,"RON":4.659515,"RSD":118.373002,"RUB":75.344593,"RWF":996.498021,"SAR":4.269458,"SBD":9.381094,"SCR":15.535163,"SDG":54.212344,"SEK":10.321788,"SGD":1.564905,"SHP":1.504318,"SLL":9566.38139,"SOS":660.536217,"SRD":8.493623,"STD":23973.578123,"SVC":9.963329,"SYP":586.510648,"SZL":16.388543,"THB":37.405732,"TJS":10.731259,"TMT":3.985992,"TND":3.274782,"TOP":2.590444,"TRY":6.1841,"TTD":7.674459,"TWD":34.853558,"TZS":2609.006788,"UAH":32.082724,"UGX":4262.396299,"USD":1.138855,"UYU":37.286527,"UZS":9368.220636,"VEF":283028.158604,"VND":26583.150642,"VUV":127.289806,"WST":3.038567,"XAF":652.530098,"XAG":0.077234,"XAU":0.000924,"XCD":3.077813,"XDR":0.81889,"XOF":660.53621,"XPF":119.925518,"YER":285.112734,"ZAR":16.292235,"ZMK":10251.064651,"ZMW":13.498889,"ZWL":367.115578}}

How Can I fix this in MagicMirror to get currency data on screen?

**Comment by yawnsde** [comment]
Hey sorry, I did not see the raised issue at all. fixer.io changed their api and required an access_key to fetch data. I changed to another api using the same source, so should be fixed now

**Comment by Dubouc** [comment]
I changed for the latest API base and add the access_key required but nothing is displayed: only LOADING.... displayed......
